services:
  api:
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server
    command:
      - --reload
  db:
    ports:
      - "127.0.0.1:5432:5432"
  db-migrate:
    volumes:
      - ./migrations:/app/migrations
  cache:
    ports:
      - "127.0.0.1:6379:6379"
