"""Make game_players.player_id nullable

Revision ID: 4c7619492f01
Revises: afee3fd9fd66
Create Date: 2024-06-11 13:47:00.428650+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c7619492f01"
down_revision: Union[str, None] = "afee3fd9fd66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("game_players", "player_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("game_players", "player_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
